project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
lang: pt
website:
  title: "Alexsandro Prado"
  site-url: "https://alexsandroprado.github.io/"
  favicon: amd
  twitter-card: true
  description: "Desvendando mistérios dos dados como Sherlock Holmes, mas com laptop e café, não lupa e cachimbo!"
  google-analytics: "GTM-T9KC9QL7"
  back-to-top-navigation: true
  reader-mode: false
  navbar:
    type: light
    background: "#000000"
    logo: "images/logo.png"
    left:
      - href: blog/index.qmd
        text: Blog
      # - href: artigos/index.qmd
      #   text: Artigos
#      - href: palestras/index.qmd
#        text: Palestras
#     - href: Ensino/index.qmd
#        text: Ensino
#      - href: software/index.qmd
#        text: Software
      # - text: Resources
      #   menu:
      #     - text: DataViz Portfolio
      #       href: dataviz_portfolio.html
      #     - text: YARDS
      #       href: https://yards.albert-rapp.de/
      #     - text: R Weekly
      #       href: https://rweekly.org/
      #     - text: R Bloggers
      #       href: https://www.r-bloggers.com/
    right:
      - icon: github
        href: https://github.com/alexsandroprado
      - icon: twitter-x
        href: https://twitter.com/alexsandroprado
      - icon: youtube
        href: https://www.youtube.com/@profalexsandroprado
      - icon: rss
        href: blog/index.xml
  page-footer:
    left: "Copyright 2023, Alexsandro Prado"
    right:
      - icon: github
        href: https://github.com/alexsandroprado
      - icon: twitter-x
        href: https://twitter.com/alexsandroprado
    background: "#000000"

date-format: "D MMMM YYYY"

format:
  html:
    theme:
      light: journal
      dark: darkly
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html

blog:
  - folder: blog
    feed: true
