project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"

website:
  title: "Alexsandro Prado"
  site-url: "https://mariecurie.com"
  navbar:
    background: "#000000"
    left:
      - href: blog/index.qmd
        text: Blog
      - href: artigos/index.qmd
        text: Artigos
      - href: palestras/index.qmd
        text: Palestras
      - href: Ensino/index.qmd
        text: Ensino
      - href: software/index.qmd
        text: Software
      - href: sobre/index.qmd
        text: Sobre
  page-footer:
    left: "Copyright 2023, Alexsandro Prado"
    right:
      - icon: github
        href: https://github.com/alexsandroprado
      - icon: twitter
        href: https://twitter.com/alexsandroprado
    background: "#000000"

date-format: "D MMMM YYYY"

format:
  html:
    theme:
      light: united
      dark: darkly
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html

