project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "*.md"
lang: pt
website:
  title: "Alexsandro Prado"
  site-url: "https://mariecurie.com"
  navbar:
    background: "#000000"
    left:
      - href: blog/index.qmd
        text: Blog
      - href: artigos/index.qmd
        text: Artigos
      - href: palestras/index.qmd
        text: Palestras
      - href: Ensino/index.qmd
        text: Ensino
      - href: software/index.qmd
        text: Software
      - text: Resources
        menu:
          - text: DataViz Portfolio
            href: dataviz_portfolio.html
          - text: YARDS
            href: https://yards.albert-rapp.de/
          - text: R Weekly
            href: https://rweekly.org/
          - text: R Bloggers
            href: https://www.r-bloggers.com/
    right:
      - icon: github
        href: https://github.com/alexsandroprado
      - icon: twitter
        href: https://twitter.com/alexsandroprado
      - icon: youtube
        href: https://www.youtube.com/@profalexsandroprado
  page-footer:
    left: "Copyright 2023, Alexsandro Prado"
    right:
      - icon: github
        href: https://github.com/alexsandroprado
      - icon: twitter
        href: https://twitter.com/alexsandroprado
    background: "#000000"

date-format: "D MMMM YYYY"

format:
  html:
    theme:
      light: united
      dark: [darkly, dark.scss]
    css: styles.css
    toc: true
    html-math-method: katex
    include-in-header:
      file: header.html

