baseurl = "/"
languageCode = "en-us"
theme = "hugo-theme-hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "post"
  # "light" or "dark"
  defaultTheme = "dark"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2
  # Enable to show reading time in minutes for posts
  showReadingTime = false  

[languages]
  [languages.en]
    title = "Alexsandro Prado"
    subtitle = "A simple theme for Hugo"
    keywords = ""
    copyright = ""
    menuMore = "Mostre mais"
    writtenBy = "Escrito por"
    readMore = "Leia mais"
    readOtherPosts = "Leia outros posts"
    newerPosts = "Novos posts"
    olderPosts = "Antigos posts"
    minuteReadingTime = "min. lidos"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "Alexsandro Prado"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "Sobre"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
        
        
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
